### ISSUE TITLE
failed to decrypt

### ISSUE THREAD

**Issue by njdro** [kmdm/ruuveal#101]
rom.zip extracted from http://dl3.htc.com/application/RUU_M7_UL_L50_SENSE60_MR_BrightstarUS_WWE_7.17.1540.51.exe

```
./fastboot getvar all
[...]
(bootloader) product: m7_ul
(bootloader) platform: HBOOT-8064
(bootloader) modelid: PN0712000
[...]
```

```
$ ./ruuveal --device m7_ul rom.zip decrypted.zip
ruuveal
-------

Large zip format detected containing 5 zipfile(s)
Invalid zip file - aborting!
failed to decrypt zip file!
Processing ZIP... 32768/51434099
```

**Comment by Sneakyghost** [comment]
You might want to use the RUU Decrypt Tool by @nkk71 over at xda-developers.com - it integrates ruuveal and unruu and bruutveal and can extract keys from the respective files most often. 
Link: https://forum.xda-developers.com/chef-central/android/tool-universal-htc-ruu-rom-decryption-t3382928

**Comment by njdro** [comment]
supplied link worked. TY
