### ISSUE TITLE
HTC Deisre 601(zara_cl) decrypt KK4.4 RUU

### ISSUE THREAD

**Issue by dsanke** [kmdm/ruuveal#84]
Hi,
I tried to decrypt this RUU : RUU_ZARA_CL_K44_SENSE55_MR_Sprint_WWE_VM_2.15.6 52.3_Radio_1.14.50.0516_NV_SPCS_5.17_003_PRL55009_ 1_release_378338_signed_2.exe
And it can be downloaded here:http://dl3.htc.com/application/RUU_ZARA_CL_K44_SENSE55_MR_Sprint_WWE_VM_2.15.6 52.3_Radio_1.14.50.0516_NV_SPCS_5.17_003_PRL55009_ 1_release_378338_signed_2.exe
But finally I got 5 zips , and none of them could by extracted.

**Comment by dsanke** [comment]
I use bruutveal and extract a key from zara_cl's KK hboot , and I have decrypt KK4.4 RUU , thanks a lot.

**Comment by FrankyXu** [comment]
Hi dsanke, could you please tell me how to extract a key from a hboot file?

**Comment by dsanke** [comment]
Hi FrankyXu,just use branch:bruteforce and follow its guide.

**Comment by FrankyXu** [comment]
Hi dsanke, thank you very much. I have extracted the key from a hboot file.
