### ISSUE TITLE
Can't extract key from HTC M9's aboot

### ISSUE THREAD

**Issue by dsanke** [kmdm/ruuveal#91]
I used "-D" to dump 7 zips but none of them can be extracted.
Then I use bruutveal to extract key from aboot.img but it fail with"Failed to determine key - Correct HBOOT/RUU pairing?"
Is there a way to decrypt HTC M9's RUU?

**Comment by MethHeadAlert** [comment]
http://www.htc.com/us/support/htc-one-m9/news/

that is where the ruu is at. I am experiencing the same issue. I have also done the -D to get the 7 files but still cannot extract.....

**Comment by dsanke** [comment]
@MethHeadAlert
unpack the hosd kernel image
then find "downloadzip" at ramdisk/sbin/
use bruutveal to extract key from downloadzip binary just like hboot image in old device
